NotAdam/Lumina

- Lumina/Excel/ExcelSheetImpl.cs
- Lumina/Excel/RowParser.cs
reduces time required to iterate over all quest records from ~43s to sub 1s on my machine.
> cache column offsets

- src/Lumina/Data/SqPackStream.cs
This should fix the issue related to issue #15 where Lumina cannot read Model files. 
The issue appears to be that Lumina was storing the MemoryStream (output) position and using that for seeking against the Reader (input).
> Fix issues related to Model memory seeking

- src/Lumina/Data/Files/Pcb/PcbListFile.cs
- src/Lumina/Data/Files/Pcb/PcbResourceFile.cs
- src/Lumina/Data/Parsing/Common.cs
As said on the tin, if you do gameData.GetFile< PcbResourceFile >( "bg/ex3/01_nvt_n4/goe/n4gb/collision/tr1617.pcb" ), you'll get a PcbResourceFile object which you can then explore via its Nodes field; if you want to explore a list.pcb, you need to use PcbListFile because they have different structures.
Future thought is to make a class to integrate both of those so you can just LoadPcb( "bg/ex3/01_nvt_n4/goe/n4gb" ) and it'll load "collision/list.pcb" within that folder, and then load all the individual PcbResourceFiles referenced by that list (potentially into a more 'useful' representation, although I'm not entirely sure what that representation would look like yet).
> Add rudimentary support for PCB files

- src/Lumina/Text/Payloads/BasePayload.cs
I was wondering why I couldn't access raw bytes. SeString only ever builds payloads with this constructor.
> Set _data in second BasePayload ctor

- src/Lumina/Data/Files/TexFile.cs
Copying the A8R8G8B8 buffer directly into the pixel data destination buffer does not work for some files that have extra data for some reason. The original method which determines which buffer is larger and only copies what is possible is working properly, so I swapped the Convert method to use this.
> Fall back to the original ProcessA8R8G8B8 method

- src/Lumina/Data/Files/Excel/ExcelDataFile.cs
- src/Lumina/Excel/ExcelSheet.cs
- src/Lumina/Excel/ExcelSheetImpl.cs
The XIV Stream Deck plugin requires the use of an embedded web server for the purposes of the plugin and interfacing with the Elgato software. As the EmbedIO server is in a different thread (for obvious reasons), data access to sheets may be called from multiple threads. This added lock prevents threads from modifying the RowParser's seek position while reading is taking place.
> Add a further lock on row parsing to prevent errors when loading from multiple threads.

- src/Lumina/Data/SqPackStream.cs
When the block in question is not compressed, `dest.Position` was not being advanced and `resetPosition` was not being honored. This commit fixes that.
> Fix ReadFileBlock not doing enough when block isn't compressed

- src/Lumina/Data/Structs/SqPackIndexHeader.cs
Fixes hash table offsets wrapping into uint range when reading files modified by TexTools.
> Fix overflow in hash table offsets

- src/Lumina/Data/Files/TexFile.cs
- src/Lumina/Data/Parsing/Tex/Buffers/A8TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/B4G4R4A4TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/B5G5R5A1TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/B8G8R8A8TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/B8G8R8X8TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/BlockCompressionTextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/L8TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/R16G16B16A16FTextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/R32G32B32A32FTextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/TextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Buffers/UnsupportedTextureBuffer.cs
- src/Lumina/Data/Parsing/Tex/Flags.cs
Cube maps are treated as having depth value of 6. 
```cs
// t1, t2, t3, and t4 effectively does the same, but the last one should be quickest.
var t1 = GetFile<TexFile>("common/graphics/texture/-caustics.tex")!.TextureBuffer.Filter(mip: 0).Filter(z: 2).Filter(format: TexFile.TextureFormat.B8G8R8A8).RawData;
var t2 = GetFile<TexFile>("common/graphics/texture/-caustics.tex")!.TextureBuffer.Filter(mip: 0, z: 2).Filter(format: TexFile.TextureFormat.B8G8R8A8).RawData;
var t3 = GetFile<TexFile>("common/graphics/texture/-caustics.tex")!.TextureBuffer.Filter(mip: 0, format: TexFile.TextureFormat.B8G8R8A8).Filter(z: 2).RawData;
var t4 = GetFile<TexFile>("common/graphics/texture/-caustics.tex")!.TextureBuffer.Filter(mip: 0, z: 2, format: TexFile.TextureFormat.B8G8R8A8).RawData;
// t5 and t6 do the …
```
> Add support for multiple mipmaps/depths for TexFile

- src/Lumina/Data/Repository.cs
- src/Lumina/GameData.cs
- src/Lumina/LuminaOptions.cs
* Parallel attempt takes 4.145s. (130ms/attempt)
* Non-parallel attempt takes 15.630s. (488ms/attempt)
```cs
Stopwatch stopwatch;
stopwatch = Stopwatch.StartNew();
for( var i = 0; i < 32; i++ )
_ = new GameData( args[ 0 ], new LuminaOptions { LoadMultithreaded = true } );
stopwatch.Stop();
Console.WriteLine( stopwatch.ElapsedMilliseconds );
stopwatch = Stopwatch.StartNew();
for( var i = 0; i < 32; i++ )
_ = new GameData( args[ 0 ], new LuminaOptions { LoadMultithreaded = false } );
stopwatch.Stop();
Console.WriteLine( stopwatch.ElapsedMilliseconds );
```
> Add LuminaOption.LoadMultithreaded, and load repo/categories in parallel

- src/Lumina/Data/Files/ScdFile.cs
- src/Lumina/Data/Parsing/Scd/ScdAttribute.cs
- src/Lumina/Data/Parsing/Scd/ScdAudio.cs
- src/Lumina/Data/Parsing/Scd/ScdCommon.cs
- src/Lumina/Data/Parsing/Scd/ScdLayout.cs
- src/Lumina/Data/Parsing/Scd/ScdSound.cs
- src/Lumina/Data/Parsing/Scd/ScdTrack.cs
This adds support to read the following sections in a scd file:
- Sound
- Track (prototype parsing)
- Audio
- Layout
- Attribute
The "Routing" section isn't currently being read as I couldn't find a parsing method for that in the game executable nor a scd file using this section in the game files.
> Add scd file reading support

- src/Lumina/Excel/ExcelModule.cs
RemoveSheetFromCache when called with no parameters will generate the name based off the sheet's name property. 
This is generally uppercase, GetSheet handles this by calling ToLowerInvariant on the name which is then passed to the ID tuple.
This change does the same for RemoveSheetFromCache.
> Use lowercase name in RemoveSheetFromCache

- src/Lumina/Data/Parsing/MdlStructs.cs
- src/Lumina/GameData.cs
- src/Lumina/Models/Models/Mesh.cs
- src/Lumina/Models/Models/Model.cs
- src/Lumina/Models/Models/Shape.cs
- src/Lumina/Models/Models/Submesh.cs
I'm being harassed by people in the Penumbra Discord to work on Xande again so that means this needs to be merged. Is it finished? Who knows!
> Pull in what we have for Xande so far

- src/Lumina/Text/Expressions/BinaryExpression.cs
- src/Lumina/Text/Expressions/ExpressionType.cs
- src/Lumina/Text/Expressions/IntegerExpression.cs
- src/Lumina/Text/Expressions/ParameterExpression.cs
- src/Lumina/Text/Expressions/PlaceholderExpression.cs
- src/Lumina/Text/Expressions/StringExpression.cs
- src/Lumina/Text/Payloads/BasePayload.cs
- src/Lumina/Text/Payloads/MacroCodes.cs
- src/Lumina/Text/SeString.cs
overrides SeStrings ToString() methods on payloads and expressions to output text using the games macrocode syntax.
this is mostly cosmetic/for display purpose as you already get the bytes from the sheets.
example output for `Addon#153` using `SeString.ToString()`:
en
`<colortype(508)><edgecolortype(509)>Discard <ennoun(Item,2,lnum1,1,1)><if([lnum2>0], (Collectability Rating: <num(lnum2)>),)>?<edgecolortype(0)><colortype(0)>`
jp
`<colortype(508)><edgecolortype(509)><if([lnum2>0],収集価値<num(lnum2)>の,)><sheet(Item,lnum1,0)>を捨てます。<br>よろしいですか？<edgecolortype(0)><colortype(0)>`
> Add SeString ToString overrides

- src/Lumina/Text/Expressions/PlaceholderExpression.cs
I ran into a FormatException because the ExpressionType enum value is formatted using X02, which doesn't work.
Casting it to the underlying type (byte) fixes the exception.
See https://dotnetfiddle.net/OfVPzo
Also, I'd like to request a release after this PR. I would like to use the new enum values that pohky added. 🙂
> Fix FormatException in PlaceholderExpression

- src/Lumina/Text/SeString.cs
reverting the output of ToString() back to RawString as the change was causing some confusion and adding a new method instead.
or should this be a property or remove it from SeString to not add to the api unnecessarily?
> Revert SeString ToString change

- src/Lumina/Data/SqPack.cs
- src/Lumina/Data/SqPackStreamPool.cs
- src/Lumina/GameData.cs
- src/Lumina/Lumina.csproj
When using multiple threads to call `GetFile<T>`, the lock was being held per `SqPack`, which effectively is a `.dat` file. Changed that to lock per file inside a `.dat` file, and added `SqPackStreamPool? GameData.StreamPool` which will reuse already opened file handles to avoid performance hit from creating handle per every file accessed.
The attached test code iterates 800,054 paths from `040000`. The test was done on 16 P-threads on 13900k.
* Before: 30s
* After: 7.9s
* After + StreamPool: 6.8s
[SqPackStreamPool_TestCode.txt](https://github.com/NotAdam/Lumina/files/14456310/SqPackStreamPool_TestCode.txt)
[SqPackStreamPool_TestResult.txt](https://github.com/NotAdam/Lumina/files/14456311/SqPackStreamPool_TestResult.txt)
* `Microsoft.Extensions.ObjectPool` has been added as a dependency. …
> Implement stream pooling and more fine grained lock

- src/Lumina/Data/Files/TexFile.cs
- src/Lumina/Data/Parsing/Tex/Buffers/TextureBuffer.cs
DT Bench: `040000/~001b31fa` has `0x8C` as `MipLevelsCount`. According to the function at `+0x224b20`, the code is applying `& 0x7F` to the value, which cannot be found in the retail game version, and checks the MSB of the byte for something.
> Repurpose MSB of MipLevelsCount

- src/Lumina/Excel/ExcelSheet.cs
- src/Lumina/Excel/NoCache.cs
This might be a special request but I have a use case where not adding read rows to the cache would be ideal.
I'm writing a Dalamud plugin that searches for translations of game content and that means that I read a lot of rows from many sheets in order to find an item that matches the search string (ex: ex: "popoto" will match "popoto", "popoto step" and "Popotoes au Gratin")
In a Dalamud context the sheet cache (and the row cache) are always kept in memory and using `ExcelModule.RemoveSheetFromCache<T>()` would be detrimental to other users of the cache.
Therefore it would simply be best for me be able to iterate over rows without loading a gigabyte of data into the cache ^^'
PS. I'm not sure why I had to add another `GetEnumerator` method, but it wouldn't compile without it
> Added option to skip caching when enumerating rows

- src/Lumina/Text/SeStringBuilder.AppendLine.cs
- src/Lumina/Text/SeStringBuilder.Presets.cs
This PR adds a `SeStringBuilder.AppendNewLine` shortcut and `SeStringBuilder.AppendLine` and its overloads.
It's mostly copy-paste but leads to a simpler API when dealing with multi-line text.
---
> Add SeStringBuilder.AppendNewLine/AppendLine

- src/Lumina/Text/Payloads/MacroCode.cs
- src/Lumina/Text/ReadOnly/ReadOnlySePayload.cs
- src/Lumina/Text/ReadOnly/ReadOnlySePayloadSpan.cs
Not sure why I made unknown macrocode throw on payload span constructor, but yeah.
> Support unknown macrocode in sestring spans and support ruby payload

- src/Lumina/Data/Parsing/Scene/HousingSettings.cs
- src/Lumina/Data/Parsing/Scene/Scene.cs
Contains parameters used by housing objects.
> Add HousingSettings struct

- src/Lumina/Data/Structs/SqPackHeader.cs
The Xbox version of FFXIV (dumped with [Collateral Damage](https://github.com/exploits-forsale/collateral-damage)) uses the codename "Lysander", as evident by the PDB path and the dat format being XXXXXX.lys.dat0.
- Since this is a console release patched via Xbox Live, there is only one dat file per category and repository.
- Platform ID of 0x4 in the indexes. 0x3 is likely PS5.
- Files work out of the box since they seem to behave exactly like Win32. Thus, all that is required is a new enum entry.
I wanted to go with the name "Xbox" for the enum, but the file path is determined by the enum value, so I guess let's just hope people read that comment...
Pics or it didn't happen (ui/uld/BagStatus_hr1.tex):
> Add Xbox support

- src/Lumina/Excel/RawRow.cs
- src/Lumina/Excel/RawSubrow.cs
For the new `RawRow` and `RawSubrow` structs, `ExcelModule.GetSheet` is throwing `SheetAttributeMissingException`:
https://github.com/NotAdam/Lumina/blob/2ce372ad3aa883b0fd991edb3ac4bef54f8530d2/src/Lumina/Excel/ExcelModule.cs#L85-L86
Adding `SheetAttribute` to these structs makes them usable.
> Fix SheetAttributeMissingException for RawRow and RawSubrow

- src/Lumina/Excel/RawSubrow.cs
Copying the [RawRow.ReadColumn](https://github.com/NotAdam/Lumina/blob/master/src/Lumina/Excel/RawRow.cs#L44) function over to the RawSubrow struct.
> Copy over ReadColumn to RawSubrow

- src/Lumina.Tests/SeStringBuilderTests.cs
- src/Lumina/Text/SeStringBuilder.cs
`SeString`s created from `SeStringBuilder` is often used right away and discarded without escaping the code scope `.ToArray` is being called. This commit adds new functions that will expose a read-only view of the internal buffer.
> Add SeStringBuilder.GetViewAsMemory/Span

- src/Lumina.Tests/SeStringBuilderTests.cs
- src/Lumina/Text/Parse/MacroStringParser.cs
* Fixed numbers not being parsed correctly if prefixed with two zeroes.
* Fixed parsing MacroString already including SeString payloads.
* Fixed parsing when `UtfEnumeratorFlags.IgnoreErrors` is set.
* Added corresponding tests.
* Added extra implementation comments.
> MacroString parser fixes (number, SeString-to-SeString, invalid sequence)

- src/Lumina/Excel/RawRow.cs
- src/Lumina/Excel/RawSubrow.cs
`page.ReadPackedBool` requires the complete Offset, so Field Offset + Row Offset.
`this.ReadPackedBool` provides the correct Field Offset, so it must have been simply an oversight calling `page.` here
> Fix ReadColumn using wrong offset

- src/Lumina/Data/Files/UldFile.cs
- src/Lumina/Data/Parsing/Uld/NodeData.cs
- src/Lumina/Data/Parsing/Uld/UldRoot.cs
- Fixed a mistake I made yesterday in the version check for TextureEntries.
- Fixed loading Timelines by skipping to the next entry. The game does it too. 🤷‍♂️
- Fixed loading some ulds by reading from the correct offset for the SecondHeader.
- Also updated node data structs based on fields in FFXIVClientStructs (using obsoletes this time 😉):
- NineGridNode.Unk1 → BlendMode
- NumericInputComponentNode.Unk1 → EndLetterId
---
These ulds can now be loaded without memory usage skyrocketing:
- ui/uld/CharaMake_Shadow.uld
- ui/uld/CharaSelect_Legacy.uld
- ui/uld/CharaSelect_Shadow.uld
- ui/uld/CharaSelect_Warning.uld
- ui/uld/CursorRect.uld
- ui/uld/GroupPoseFrame9grid001.uld
- ui/uld/GroupPoseFrame9grid002.uld
- ui/uld/GroupPoseFrame9grid003.uld
- ui/uld/GroupPoseGuide.uld
- …
> More Uld fixes

- .github/workflows/build.yml
- src/Lumina.Tests/ReadOnlySeStringTests.cs
- src/Lumina.Tests/SeStringBuilderTests.cs
- src/Lumina/Data/Language.cs
- src/Lumina/Text/ReadOnly/ReadOnlySeString.cs
- src/Lumina/Text/ReadOnly/ReadOnlySeStringSpan.cs
- src/Lumina/Text/SeStringBuilder.InterpolatedStringHandler.cs
* `ReadOnlySeString.ToString` and `ReadOnlySeStringSpan.ToString` now returns extracted text only without soft hyphens.
* `ReadOnlySeString.ToMacroString` and `ReadOnlySeStringSpan.ToMacroSpan` has been added.
* `ReadOnlySeString.ToString(string? format, IFormatProvider? formatProvider = null)` has been added. `formatProvider` is unused, and for `format`, empty string or `t` for text w/o SHY, `y` for text w/ SHY, and `m` for macro string is supported.
* `ReadOnlySeString.Format` has been added, which will accept a format string but will append `ReadOnlySeString/Span`s as-is without going through its string representation. Nothing at all, empty string or `r` can be specified for the ROSS' format to append it as-is, or `t`, `y`, or `m` to append it formatted.
* …
> ReadOnlySeString updates

- src/Lumina/Data/Files/Pcb/PcbResourceFile.cs
1. Float 16 vertices are based on the bounding box dimensions and location ([Reference](https://github.com/SapphireServer/Sapphire/blob/bf3368224a00c180cbb7ba413b52395eba58ec0b/src/tools/pcb_reader/main.cpp#L375))
2. The count starts at 0 for whatever reason so there should be 1 resource node to read (Reference: `bg/ffxiv/sea_s1/twn/common/collision/s1t0_iw0_lip2.pcb`, https://github.com/SapphireServer/Sapphire/blob/bf3368224a00c180cbb7ba413b52395eba58ec0b/src/tools/pcb_reader/pcb.h#L12)
> Fix PcbResourceFile

- src/Lumina/Text/Payloads/LinkPayloadType.cs
- src/Lumina/Text/Payloads/MacroCode.cs
This PR adds:
- `MacroCode.SheetSub`
- `LinkMacroPayloadType.Description`
- `LinkMacroPayloadType.WKSPioneeringTrail`
- `LinkMacroPayloadType.MKDLore`
> Update MacroCode and LinkMacroPayloadType

- src/Lumina/Data/Parsing/Tex/Buffers/BlockCompressionTextureBuffer.cs
Currently it is returning RGBA when the function call is expecting a return of BGRA
> Correct color from conversion

- src/Lumina/Data/Files/TexFile.cs
See also:
- https://github.com/aers/FFXIVClientStructs/blob/b41eccb6fd30bf714091853b8e04d1613c39229d/FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Texture.cs#L83-L85
- https://github.com/xivdev/Penumbra/blob/23c0506cb875f8613513f4169630eeb6549cc6ef/Penumbra/Import/Textures/TexFileParser.cs#L250-L252
> Add BC4 and BC6H texture formats
